version: '3'

services:
  database:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env

  backend:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/wsgi-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - database

volumes:
  static_volume: {}
