version: '3'

services:
  database:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/production:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/wsgi-entrypoint.sh
    expose:
      - 8000
    depends_on:
      - database

volumes:
  static_volume: {}
