version: '3'

services:
  database:
    image: registry.redhat.io/rhscl/postgresql-12-rhel7
    restart: always
    env_file:
      - .env

  backend:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    entrypoint: /app/backend/wsgi-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - database
