version: '3'

services:
  database:
    image: dashboard_database:latest
    container_name: dashboard_database
    image: registry.redhat.io/rhscl/postgresql-12-rhel7
    env_file:
      - .env

  frontend:
    image: dashboard_frontend:latest
    container_name: dashboard_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    image: dashboard_backend:latest
    container_name: dashboard_backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    entrypoint: /app/backend/wsgi-entrypoint.sh
    expose:
      - 8000
    depends_on:
      - database
