version: '3'

services:
  dashboard-database:
    image: dashboard-database:latest
    container_name: dashboard-database
    image: postgres
    env_file:
      - .env

  dashboard-backend:
    image: dashboard-backend:latest
    container_name: dashboard-backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    entrypoint: ./wsgi-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - dashboard-database
