version: '3'

services:
  dashboard-database:
    image: postgres
    container_name: dashboard-database
    env_file:
      - .env

  dashboard-backend:
    image: dashboard-backend:latest
    container_name: dashboard-backend
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ./wsgi-entrypoint.sh
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - dashboard-database
