name: docker-compose-actions-workflow
on:
  pull_request:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the stack
        run: docker-compose -f docker-compose-test.yml up --build --detach

      - name: Check containers
        run: docker ps

      - name: Print docker-compose logs
        run: docker-compose -f docker-compose-test.yml logs

      - name: Install capture-website-cli
        shell: bash
        run: npm install --global capture-website-cli

      - name: Screenshot Website
        shell: bash
        run: capture-website http://172.17.0.1:80 --output ./screenshot.png --full-page

      - name: Upload screenshot
        uses: actions/upload-artifact@v3
        with:
          name: dashboard-home
          path: ./screenshot.png

      - name: Docker-compose down
        run: docker-compose -f docker-compose-test.yml down
